#!/usr/bin/env bash

source .env

CUSTOMCONF="
RUN_USER = ${GOGS_APP_RUN_USER}
[server]
EXTERNAL_URL = ${GOGS_APP_EXTERNAL_URL}
DOMAIN = ${GOGS_APP_DOMAIN}
HTTP_PORT = ${GOGS_APP_HTTP_PORT}
ENABLE_GZIP = ${GOGS_APP_ENABLE_GZIP}

[repository]
ROOT = ${GOGS_APP_ROOT}

[database]
TYPE = ${GOGS_APP_TYPE}
PATH = ${GOGS_APP_DB_PATH}

[session]
PROVIDER = ${GOGS_APP_PROVIDER}

[security]
INSTALL_LOCK = ${GOGS_APP_INSTALL_LOCK}
SECRET_KEY = "${GOGS_APP_SECRET_KEY}"
"

echo "$CUSTOMCONF"
